#!/usr/bin/env sh
#
# Perform a package build.
#
# A release consists of bumping the package version (patch, minor, or major), creating a git
# tag with the new version and pushing the changes to the configured remote repository.
#
# The CI/CD pipeline should trigger off the newly tagged version in the repository and kick off
# the deployment process for this package using the commit corresponding to the new version.
