#!/usr/bin/env sh
#
# Generate changelog for the package.
#
# This uses https://github.com/github-changelog-generator/github-changelog-generator and
# requires 'CHANGELOG_GITHUB_TOKEN' environment variable.

set -e

test -n "$(command -v github_changelog_generator 2> /dev/null)" || (echo 'Required command "github_changelog_generator" not found' && exit 1)
test -n "${CHANGELOG_GITHUB_TOKEN}" || (echo "ERROR: 'CHANGELOG_GITHUB_TOKEN' environment variable does not exist" && exit 1)

github_changelog_generator -u {{ cookiecutter.repo_owner }} -p {{cookiecutter.repo_name }}
